device: cuda
path_to_data: "data/"
save_path: "output/"
model:
  backbone: "ReFineNet"
  weights: "https://github.com/fuzailpalnak/building-footprint-segmentation/releases/download/alpha/refine.zip"
data_params:
  resize: [1024, 2048]
polygon_size_filter:
  min_size: 200
